name: Build the app and run the tests-Student registry app 1

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Build the app    
      run: npm install
      
    - name: Run the Unit Tests 
      run: npm run test
